create database CLINICMANAGEMENT

create	table MEDICAL(
	MEDICALID VARCHAR(15) NOT NULL PRIMARY KEY,
	PATIENTNAME NVARCHAR(50) NULL,
	AGE INT NULL,
	GENDER NVARCHAR(10) NULL,
	OCCUPATION NVARCHAR(50) NULL,
	DOCTOR NVARCHAR(50) NULL,
	DATEAPM DATE NULL,
	CLINIC INT NULL,
	NOTE NVARCHAR(100) NULL
)